export enum TodoActionTypes {
    FETCH_DATA = "FETCH_DATA",
    FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS",
    ERROR = "FETCH_DATA_ERROR",
    CREATE_TODO = "CREATE_TODO",
    UPDATE_TODO = "UPDATE_TODO",
    DELETE_TODO = "DELETE_TODO",
    TOGGLE_TODO = "TOGGLE_TODO",
}
